Add GuestNetwork Connected numbers sensor entity #790
Vaskivskyi/ha-asusrouter pull request #850
Opened 2024-08-21 12:34 UTC by GaryHuang-ASUS

Add guest network connected devices number

2024-08-21 21:21 UTC, Vaskivskyi requested changes
Hey, Gary. Thanks for your work! I have only one comment. Please, take a look. Otherwise, everything is good

2024-08-21 21:21 UTC, Vaskivskyi commented on custom_components/asusrouter/const.py
> +        extra_state_attributes={
We better remove the whole `devices` list from the state attributes for the guest network. It contains all the devices connected and will take too much database space

2024-08-22 03:57 UTC, GaryHuang-ASUS commented on custom_components/asusrouter/const.py
> +        extra_state_attributes={
Based on your suggestion, I have tried removing the `devices` list from `extra_state_attributes` and observed the changes in the `state_attributes` table in the database. Indeed, only the Connected Devices data remains updated(insert when device connected or disconnected).

2024-08-22 04:00 UTC, GaryHuang-ASUS commented on custom_components/asusrouter/const.py
> +        extra_state_attributes={
By the way, I would like to know where these data are written into the database and how it is correctly retrieved and rendered to the frontend. 

While tracing the code, I only saw update_clients calling the API via the asusrouter(from ARDevice and call async_get_clients) package to fetch new data. The device's coordinator then updates its data attribute, but I didn't see where the data gets written to the database and what information(schema in the text part) is being recorded.

Thanks.

2024-08-22 04:14 UTC, GaryHuang-ASUS commented on custom_components/asusrouter/const.py
> +        extra_state_attributes={
By the way, I noticed that the loop was redundant, so I removed it and kept only the condition

Thanks.

2024-08-22 06:26 UTC, Vaskivskyi commented on custom_components/asusrouter/const.py
> +        extra_state_attributes={
All the DB-related tasks are handled by the Home Assistant itself. Integration only provides standardized entry points and interfaces.

E.g. when the integration is found by HA, it searches for the `async_setup_entry` function in [`__init__.py`](https://github.com/Vaskivskyi/ha-asusrouter/blob/dev/custom_components/asusrouter/__init__.py). As you can see, this one initializes a router (`ARDevice` instance) and tells HA what platforms to load (e.g. `sensor`, `switch` and so on). All those just use callbacks or defined HA function names for the communication.

But in general, integration does not have any access neither to the DB nor to the frontend

In principle, there are [HA dev docs](https://developers.home-assistant.io/docs/development_index). They help with most of the basics but do not have all the examples.

2024-08-22 06:26 UTC, Vaskivskyi approved these changes

2024-08-22 06:28 UTC, Vaskivskyi commented
I think it's ready. Thanks! :+1:

2024-08-22 06:30 UTC, merged